-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: guildmaster (/d/damned/guilds/paladin/paladin_gm#8)
Error in object: /d/damned/guilds/paladin/paladin_gm#8 (Wed Nov 27 03:12:30 2019)
> *call_other() couldn't find object

File: /std/living/combat.c           line 758

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /d/damned/guilds/paladin/paladin_gm#8
     Program: /std/monster.c
     File:               /std/monster.c line 131

2:   continue_attack() in /d/damned/guilds/paladin/paladin_gm#8
     Program: /std/living/combat.c
     File:         /std/living/combat.c line 304

3:   execute_attack() in /d/damned/guilds/paladin/paladin_gm#8
     Program: /std/living/combat.c
     File:         /std/living/combat.c line 643

4:   do_criticals() in /d/damned/guilds/paladin/paladin_gm#8
     Program: /std/living/combat.c
     File:         /std/living/combat.c line 758


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: guildmaster (/d/damned/guilds/paladin/paladin_gm#38)
Error in object: /d/damned/guilds/paladin/paladin_gm#38 (Wed Nov 27 03:21:25 2019)
> *call_other() couldn't find object

File: /std/living/combat.c           line 758

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /d/damned/guilds/paladin/paladin_gm#38
     Program: /std/monster.c
     File:               /std/monster.c line 131

2:   continue_attack() in /d/damned/guilds/paladin/paladin_gm#38
     Program: /std/living/combat.c
     File:         /std/living/combat.c line 304

3:   execute_attack() in /d/damned/guilds/paladin/paladin_gm#38
     Program: /std/living/combat.c
     File:         /std/living/combat.c line 643

4:   do_criticals() in /d/damned/guilds/paladin/paladin_gm#38
     Program: /std/living/combat.c
     File:         /std/living/combat.c line 758


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:13 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:14 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:15 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:16 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:17 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:18 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:19 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:20 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:21 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:22 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:23 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:24 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:25 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:26 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:27 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:28 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:29 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:30 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:31 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:32 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:33 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:34 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:35 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:36 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:37 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:38 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:39 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:40 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:41 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:42 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:43 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:44 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:45 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:46 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:47 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:48 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:49 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:50 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:51 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:52 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:53 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:54 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:55 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:56 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:57 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:58 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:30:59 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:00 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:01 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:02 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:03 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:04 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:05 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:06 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:07 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:08 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:09 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:10 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:11 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:12 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Heart beat error in: parnellii (/std/user#3)
Error in object: /std/occ_picker#4 (Sun Dec  1 15:31:13 2019)
> *Could not open /save/adm/objects/saveall/p/parnellii/parnellii_0.o.tmp for a save.

File: /std/Object.c                  line 222

Traceback
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
1:   heart_beat() in /std/user#3
     Program: /std/user.c
     File:                  /std/user.c line 586

2:   add_crash_items() in /daemon/save_all_d
     Program: /daemon/save_all_d.c
     File:         /daemon/save_all_d.c line 53

3:   save_me() in /std/occ_picker#4
     Program: /std/Object.c
     File:                /std/Object.c line 222


